[package]
name = "explotty"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.98"
eframe = "0.32.0"
egui_extras = "0.32.0"
env_logger = "0.11.8"
font-kit = "0.14.3"
log = "0.4.27"
portable-pty = "0.9.0"
walkdir = "2.5.0"
